### ISSUE TITLE
issue: Docker does not start after updating from v0.9.6 to v.0.10.1 [ImportError: cannot import name 'get_ssrf_safe_session']

### ISSUE THREAD

**Issue by ChessMastermind** [open-webui/open-webui#26392]
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I have also searched in the CLOSED issues AND CLOSED discussions and found no related items (your issue might already be addressed on the development branch!).
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.10.1

### Operating System

Debian GNU/Linux 13 (trixie)

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

After updating open-webui should normally start. But it doesn't?

### Actual Behavior

Crash during start of container. Followed by continuous restart of container

### Steps to Reproduce

1. Have version [v0.9.6](https://github.com/open-webui/open-webui/releases/tag/v0.9.6) 
2. Run "docker compose up -d --pull always" 
3. And after this docker never came up. 

### Logs & Screenshots

compose.yaml:
version: '3.8'

services:
open-webui:
image: ghcr.io/open-webui/open-webui:main
container_name: open-webui
restart: always
ports:
- "0.0.0.0:3000:8080"
volumes:
- /home/open-webui/data:/app/backend/data
- /home/open-webui/utils.py:/app/backend/open_webui/retrieval/web/utils.py:ro,Z
environment:
- GLOBAL_LOG_LEVEL="DEBUG"
- HOME=/app/backend/data
- WEBUI_SECRET_KEY=***
- BYPASS_MODEL_ACCESS_CONTROL=True
security_opt:
- no-new-privileges:true
labels:
- "io.containers.autoupdate=registry"

open-webui@small-pc:~$ docker logs open-webui
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
WARNI [open_webui.env]

WARNING: CORS_ALLOW_ORIGIN IS SET TO '*' - NOT RECOMMENDED FOR PRODUCTION DEPLOYMENTS.

WARNI [langchain_community.utils.user_agent] USER_AGENT environment variable not set, consider setting it to identify your requests.
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/local/lib/python3.11/site-packages/uvicorn/__main__.py", line 4, in <module>
uvicorn.main()
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1569, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1490, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1353, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 907, in invoke
return callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 433, in main
run(
File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 606, in run
server.run()
File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 75, in run
return asyncio_run(self.serve(sockets=sockets), loop_factory=self.config.get_loop_factory())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uvicorn/_compat.py", line 30, in asyncio_run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 79, in serve
await self._serve(sockets)
File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 86, in _serve
config.load()
File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 441, in load
self.loaded_app = import_from_string(self.app)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
module = importlib.import_module(module_str)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/app/backend/open_webui/main.py", line 120, in <module>
from open_webui.events import (
File "/app/backend/open_webui/events.py", line 15, in <module>
from open_webui.utils.webhook import post_webhook
File "/app/backend/open_webui/utils/webhook.py", line 11, in <module>
from open_webui.retrieval.web.utils import get_ssrf_safe_session, validate_url
ImportError: cannot import name 'get_ssrf_safe_session' from 'open_webui.retrieval.web.utils' (/app/backend/open_webui/retrieval/web/utils.py)

### Additional Information

I am sorry for not providing pull request. It is late at night for me, I will try to look further into detail in around 12 hours. Again sorry, any help would be greatly appreciated. Thank you again for making such an amazing tool.

**Comment by Classic298** [comment]
This isn't a bug in Open WebUI, it's caused by a bind mount in your `compose.yaml`:

```yaml
volumes:
  - /home/open-webui/utils.py:/app/backend/open_webui/retrieval/web/utils.py:ro,Z
```

You're mounting your own `utils.py` read-only on top of the application's `retrieval/web/utils.py`. That overlay replaces the real module inside the container with your older copy.

In v0.10.1, `open_webui/utils/webhook.py` imports `get_ssrf_safe_session` from `retrieval/web/utils.py`. That function exists in the shipped file, but your overlaid copy predates it and doesn't define it, so the import fails and the container crash-loops:

```
ImportError: cannot import name 'get_ssrf_safe_session' from 'open_webui.retrieval.web.utils'
```

Fix: remove that volume line (or replace your custom `utils.py` with the current v0.10.1 version that includes `get_ssrf_safe_session`). Overlaying a single internal source file across version upgrades will keep breaking like this whenever that file's API changes, so if you maintain a local patch, rebase it onto each release rather than pinning an old copy.

**Comment by ChessMastermind** [comment]
Thank you soo much!!! I am very sorry for wasting your time.
