### ISSUE TITLE
issue: "'State' object has no attribute 'config'" in all chats after upgrade from 0.9.6 to 0.10.2 on a single user instance

### ISSUE THREAD

**Issue by arbv** [open-webui/open-webui#26787]
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I have also searched in the CLOSED issues AND CLOSED discussions and found no related items (your issue might already be addressed on the development branch!).
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.10.2

### Ollama Version (if applicable)

n/a

### Operating System

NixOS 26.05

### Browser (if applicable)

n/a (the issue is reproducible regardless of the browser)

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

New chats work as expected.

### Actual Behavior

The instance is completely unusable now, each chat results in "'State' object has no attribute 'config'".

<img width="1218" height="235" alt="Image" src="https://github.com/user-attachments/assets/06d2bdb7-9442-455c-93ca-afc3f5f58dc5" />

### Steps to Reproduce

All what I have done is upgraded my instance from 0.9.6 to 0.10.2. I have a quite old instance which was gradually upgraded for over a year now (no major version skips).

### Logs & Screenshots

<img width="1218" height="235" alt="Image" src="https://github.com/user-attachments/assets/2ec77e89-4e4f-4a52-aae6-1fa35e9cf5f8" />

Service logs:

```
...
лип 03 13:57:32 cauldron open-webui[102317]: 
лип 03 13:57:32 cauldron open-webui[102317]: v0.10.2 - building the best AI user interface.
лип 03 13:57:32 cauldron open-webui[102317]: 
лип 03 13:57:32 cauldron open-webui[102317]: https://github.com/open-webui/open-webui
лип 03 13:57:32 cauldron open-webui[102317]: 
лип 03 13:57:32 cauldron open-webui[102317]: INFO:     Started server process [1]
лип 03 13:57:32 cauldron open-webui[102317]: INFO:     Waiting for application startup.
лип 03 13:58:17 cauldron open-webui[102317]: 2026-07-03 10:58:17.170 | ERROR    | open_webui.main:process_chat:1512 - Error processing chat payload: 'State' object has no attribute 'config'
```

**Comment by arbv** [comment]
I am aware of #26627 , but I believe that this one is a different issue as it has nothing to do with interface settings.

**Comment by Classic298** [comment]
This error can no longer originate from Open WebUI core. 0.10 is a full backend rewrite in which the old in-memory config object (`app.state.config`) was removed entirely; configuration now lives in a database-backed key-value store. You can verify this yourself: `git grep "state.config" v0.10.2 -- backend/` returns nothing, so there is no code path left in 0.10.2 that could raise `'State' object has no attribute 'config'`.

What can still raise it is code loaded from your database at runtime: installed functions (filters, pipes, actions) and tools. Anything written against the pre-0.10 plugin API that accesses `request.app.state.config.<SETTING>` now fails with exactly this AttributeError. A globally enabled filter runs on every chat and a pipe-based model fails on every request, which matches "every chat is broken". Since your instance has been upgraded gradually for over a year, it almost certainly carries at least one such function.

To confirm and recover:

1. Start the instance once with the environment variable `SAFE_MODE=true`. This deactivates all installed functions at startup. If chats work again, one of your functions is the cause.
2. To identify which one, set `GLOBAL_LOG_LEVEL=DEBUG` and send a chat: the log will contain a line naming the failing function id (for filters, `Error in inlet handler <function_id>`) right before the error you posted.
3. Update the offending function to the 0.10 API (config reads must go through the new config system or the function's own valves) or fetch an updated version from wherever you installed it, then re-enable it.

You are right that this is not the same issue as #26627: that was a leftover reference to the old config object in the settings endpoint and was already fixed in 0.10.2. Your error comes from installed plugin code, not from core, so there is nothing to fix in Open WebUI itself here.

**Comment by arbv** [comment]
@Classic298 You were right. One of my custom filters caused this. How could I get the application config now in my plugin?

```python
        prompt = "\n\n"

        if web_search_enabled:
            prompt = prompt + self._get_web_search_prompt(
                __request__.app.state.config.WEB_SEARCH_ENGINE
            )

```

**Comment by Classic298** [comment]
without seeing your whole filter i cannot help. best throw an ai agent at it and tell it to fix it with the context here and by checking the open webui backend for the correct imports

**Comment by arbv** [comment]
@Classic298 Nevermind, I have figured out:

```
from open_webui.models.config import Config

...
        if web_search_enabled:
            prompt = prompt + self._get_web_search_prompt(
                await Config.get("web.search.engine")
            )
```

Thank you!
