### ISSUE TITLE
issue: PostgreSQL TLS startup regression in v0.9

### ISSUE THREAD

**Issue by attilaolah** [open-webui/open-webui#24040]
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I have also searched in the CLOSED issues AND CLOSED discussions and found no related items (your issue might already be addressed on the development branch!).
- [x] I am using the latest version of Open WebUI.

### Installation Method

Other

### Open WebUI Version

0.9.1

### Operating System

Kubernetes (Helm) deployment

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

(Forgive the AI-generated text below, I wanted to make sure all the details are properly included.)

---

## Summary
After upgrading Open WebUI from `v0.8.12` to `v0.9.0`, startup fails when `DATABASE_URL` is configured for PostgreSQL TLS.

This appears to be a regression introduced by the move from psycopg2-only runtime behavior to asyncpg runtime behavior combined with an early psycopg2 migration step.

## Affected Versions
- Works: `v0.8.12`
- Fails: `v0.9.0`

## Environment
- Kubernetes deployment
- Postgres reachable via in-cluster service (`open-webui-postgres:5432`)
- `DATABASE_URL` provided via secret
- Container runs as non-root user (`uid=10000`) with `HOME=/root`

### Old URL (worked previously)
`postgresql://.../postgres?sslmode=verify-full&sslrootcert=/etc/tls/ca.crt&sslcert=/etc/tls/tls.crt&sslkey=/etc/tls/tls.key`

### Failure in v0.9.0
`TypeError: connect() got an unexpected keyword argument 'sslrootcert'`

### Why
In `v0.9.0`, runtime DB access uses `sqlalchemy+asyncpg`. The URL parser strips `ssl` / `sslmode` but leaves `sslrootcert`, `sslcert`, `sslkey` in the query string, which then reach asyncpg and crash.

### Updated URL used to test asyncpg-compatible format
`postgresql://.../postgres?sslmode=verify-full`

### Failure in v0.9.0
`OperationalError: root certificate file "/root/.postgresql/root.crt" does not exist`

### Why this is unexpected
`v0.9.0` still performs startup migration via psycopg2/peewee before app runtime is fully up. With `sslmode=verify-full` and no explicit `sslrootcert` query parameter, libpq defaults to `~/.postgresql/root.crt`.

In this container, process user is `uid=10000` and `HOME=/root`, while `/root` is `0700` (root-only). So the app user cannot access `/root/.postgresql/*`.

## Test Performed: mount certs where libpq expects
I mounted a secret with:
- `ca.crt -> /root/.postgresql/root.crt`
- `tls.crt -> /root/.postgresql/postgresql.crt`
- `tls.key -> /root/.postgresql/postgresql.key`

Result: same startup error (`root certificate file "/root/.postgresql/root.crt" does not exist`).

Likely cause: user `10000` cannot traverse `/root` due permissions, so libpq cannot read files there.

## Expected Behavior
- `v0.9.0` should accept TLS Postgres URLs that previously worked in `v0.8.x`, or provide a migration path that does not break startup.
- Startup should not fail due incompatible SSL parameter handling between psycopg2 and asyncpg.
- Non-root container users should have a supported cert lookup path for libpq when `sslmode=verify-full` is used.

## Actual Behavior
- App crashes during startup before becoming ready.
- Two blocking paths observed:
  1. asyncpg receives unsupported query params (`sslrootcert`, etc.)
  2. psycopg2 migration step falls back to `~/.postgresql` path that is not readable for container user

## Suggested Fix Directions
1. Normalize/strip **all** SSL-file query params (`sslrootcert`, `sslcert`, `sslkey`, `sslcrl`) before asyncpg URL creation.
2. For psycopg2 migration path, avoid relying on `~/.postgresql` default under non-root runtime:
   - pass explicit readable cert paths, or
   - set `HOME` to readable directory with mounted certs, or
   - support `sslrootcert=system`/equivalent where applicable, or
   - run migration with the same TLS config surface as runtime.
3. Add regression tests for:
   - `DATABASE_URL` containing psycopg2/libpq-style SSL params
   - non-root container + `sslmode=verify-full`.

### Actual Behavior

Open WebUI crashes at startup.

## Minimal Repro
1. Deploy `v0.9.0` with PostgreSQL and TLS-enabled `DATABASE_URL`.
2. Use URL style that previously worked in `v0.8.12`:
   `...?sslmode=verify-full&sslrootcert=...&sslcert=...&sslkey=...`
3. Observe startup crash with asyncpg `sslrootcert` keyword error.
4. Change to `...?sslmode=verify-full` only.
5. Observe startup crash in psycopg2 migration with `~/.postgresql/root.crt` lookup.

### Logs & Screenshots

```
… return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 143, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3317, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 448, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1272, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    with util.safe_reraise():
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 175, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 389, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 667, in connect
    return dialect.connect(*cargs_tup, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 630, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 955, in connect
    await_only(creator_fn(*arg, **kw)),
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: connect() got an unexpected keyword argument 'sslrootcert'

Application startup failed. Exiting.
```

**Comment by attilaolah** [comment]
As a workaround, I now set `HOME` to `/home/app` and mount the Postgres certs at the default location in the home dir, but this feels somewhat brittle, it would be nice if once again we had a stable API for providing postgres connection certificates.

**Comment by attilaolah** [comment]
While mounting the TLS cert & key to the expected location works, having the client verify the server's CA is now no longer possible with a dedicated CA so the CA needs to be added to the system store.

The simple alternative is to point the system store to the internal CA that signed the Postgres certificate, however that breaks OIDC login as the same certificate is then used to validate the IDP.

So the workaround that works with OIDC _and_ Postgres CA validation is to add the internal CA to the system trust store in an init container. The existing copy-data init container provided with the Helm chart works for this.

That said, I'd still be happier if we could provide the Postgres CA, certificate & key like we could with 0.8 versions.

**Comment by attilaolah** [comment]
@tjbck which release or commit did fix the issue here?

I just upgraded to 0.9.5 and apparently the workaround of injecting TLS credentials in the startup container (https://github.com/open-webui/open-webui/issues/24040#issuecomment-4324466791) is still necessary to get proper mTLS with Postgres. I also didn't see anything in the release changelog relating to how Postgres TLS is being configured.
