### ISSUE TITLE
issue: Ask / Explain popups no longer work

### ISSUE THREAD

**Issue by druellan** [open-webui/open-webui#20146]
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I have also searched in the CLOSED issues AND CLOSED discussions and found no related items (your issue might already be addressed on the development branch!).
- [x] I am using the latest version of Open WebUI.

### Installation Method

Git Clone

### Open WebUI Version

0.6.43

### Operating System

Windows 10 / Ubuntu 24.04.1 LTS

### Browser (if applicable)

Chrome / Firefox

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

When I select a fragment of a text in the model responses, a popup shows and I can ASK or EXPLAIN the answer. If I click on ASK or EXPLAIN, the model provides extra information about the text selected.

### Actual Behavior

The popup shows up, but trying to use ASK or EXPLAIN results in an error message `An error occurred while fetching the explanation` and nothing happens.

### Steps to Reproduce

1. Select some text from the model answer
2. Wait for the ASK / EXPLAIN popup to show up
3. Select an option

### Logs & Screenshots

The browser network activity shows a call to: `/api/chat/completions` returning a 400 server error with the json `{"detail":"'NoneType' object has no attribute 'get'"}`

OWUI console shows only this line: `2025-12-23 15:23:39.240 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 127.0.0.1:53721 - "POST /api/chat/completions HTTP/1.1" 400`

### Additional Information

I'm using external models using the OpenAI completions API.
Tested locally via GIT clone and in a server using Docker.
Tested with different models but ALL of them external models (no ollama models)
Might be related to this bug report: https://github.com/open-webui/open-webui/issues/15579

**Comment by druellan** [comment]
The issue was confirmed by another user in Discord.

**Comment by Ithanil** [comment]
I think the following log message is correlated with the issue:

`open_webui.main:chat_completion:1670 - Error processing chat metadata: 'NoneType' object has no attribute 'get'`

It has level DEBUG, so likely why @druellan didn't see it in his logs. But it matches what he observed on the browser console. 

EDIT: Likely introduced by https://github.com/open-webui/open-webui/commit/f1bf4f20c53e6493f0eb6fa2f12cb84c2d22da52

**Comment by silentoplayz** [comment]
I am also able to reproduce this issue on the latest `dev` commit. Sending a message to the model this way results in a failed request to the `/api/chat/completions` endpoint. I have tested this with my llama.cpp server external connection in Open WebUI.

<img width="2092" height="1176" alt="Image" src="https://github.com/user-attachments/assets/1bcf6c44-6c07-4b52-aa39-c60e17efb332" />

```http
[HTTP/1.1 400 Bad Request 10ms]
```
```js
detail	"'NoneType' object has no attribute 'get'"
```
<img width="2301" height="528" alt="Image" src="https://github.com/user-attachments/assets/3a03316b-b9e5-4858-b7d5-c3d9264ccca4" />

**Comment by Classic298** [comment]
fixed by https://github.com/open-webui/open-webui/pull/20212

**Comment by Classic298** [comment]
fixed in dev
