### ISSUE TITLE
issue: RAG with gemma-3-12b-instruct causes infinite loop and HTTPException "list object has no attribute 'get'" error

### ISSUE THREAD

**Issue by dev-jonathan** [open-webui/open-webui#17213]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Git Clone

### Open WebUI Version

v0.6.26 most recent commit

### Operating System

Windows

### Browser (if applicable)

Brave

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

Expected Behavior
Using the gemma-3-12b-instruct model with RAG enabled in the latest OpenWebUI (local setup), the system should process the request and return a response without getting stuck.

### Actual Behavior

Actual Behavior
The system enters an infinite loop and no response is returned. The error in the logs shows:
fastapi.exceptions.HTTPException: 400: 'list' object has no attribute 'get'
with a message indicating "Developer instruction is not enabled for models/gemma-3-12b-it".

obs: Without RAG, the gemma-3-12b-instruct model works fine. Also, RAG works correctly with the gemini-2.0-flash model, so the issue seems to be specific to the gemma-3-12b-instruct model combined with RAG.

### Steps to Reproduce

Steps to Reproduce

Use the latest OpenWebUI version locally with Conda and Node.js.

Set the model to gemma-3-12b-instruct and activate RAG.

Use embeddings from qwen3-embedding running locally on LM Studio and Google AI Studio free API  as backend.

Send a request in a chat and observe the infinite loop and error in the logs.

### Logs & Screenshots

<img width="1208" height="824" alt="Image" src="https://github.com/user-attachments/assets/89f31574-c3ea-4f38-bad6-9804c884082e" />

**Comment by tjbck** [comment]
Is the inference provider openai compatible? the format shown above does not follow the spec.

**Comment by tjbck** [comment]
1bc9711afd2b72cd07c4e539a83783868733767c
