### ISSUE TITLE
v0.5.7 - OpenAI packages versioning issue

### ISSUE THREAD

**Issue by DmitriyAlergant-T1A** [open-webui/open-webui#8943]
# Bug Report

## Installation Method

Docker, v 0.5.7

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Current Behavior:

Certain custom functions that relied on pre-packaged OpenAI SDK no longer work in v0.5.7.

Example: https://openwebui.com/f/hasanraiyan/openai but also several others that relied on "import openai" SDK rather then doing their own http queries.

There is an error on deploying the function (as it attempts to fetch a list of models):

```
[ERROR: Client.__init__() got an unexpected keyword argument 'proxies']
```

## Expected Behavior:

Functions that relied on pre-packaged OpenAI SDK (import openai) continue to work.  They worked till recently (at least till 0.5.4)

## Description

**Bug Summary:**

This is a well-known OpenAI client error related to versioning conflicts of their SDK and httpx package:
https://community.openai.com/t/error-with-openai-1-56-0-client-init-got-an-unexpected-keyword-argument-proxies/1040332/2

A solution is either to upgrade the SDK to 1.55.3 or 1.56.1, or to downgrade httpx.

## Reproduction Details

**Steps to Reproduce:**

Clear-case, not dependent on any community functions. Attempt to create the following function
```
import openai


class Pipe:

    def __init__(self):
        self.type = "manifold"
        self.id = "test"
        self.name = "test/"

        self.client = openai.OpenAI()
```

An error "Client.__init__() got an unexpected keyword argument 'proxies'" comes up.

**Comment by DmitriyAlergant-T1A** [comment]
Update:  it's broken since 0.5.5.        Still works in 0.5.4 and below.

P.S> No idea how built-in OpenAI integration connection still works. It does work indeed, only custom functions using OpenAI SDK are broken.

**Comment by rgaricano** [comment]
It seem that is an openai python lib dependencies issue ( https://github.com/openai/openai-python/issues/1903 )
the solution for workaround is downgrade httpx to 0.27.2  (httpx==0.27.2)
check your versions libs.

**Comment by James030913** [comment]
Same issue here

**Comment by DmitriyAlergant-T1A** [comment]
@tjbck I thought of submitting a PR (even for requirements.txt) but frankly there is nothing even to submit except a dummy commit.  The issue should self-resolve with the next build...

- Official release docker image [open-webui/open-webui:main] 0.5.7 - the issue reproduces
- Fresh local docker build from the "main" branch - the issue no longer reproduces.   

Probably some PyPi packages updates in last 5 days may have fixed it...   In the future, consider freezing packages versions to requirements.txt?

Any plans when 0.5.8 may be coming up?

**Comment by DmitriyAlergant-T1A** [comment]
Verified, the issue is solved (at least in 0.5.10), thanks.
