### ISSUE TITLE
issue: Open WebUI v0.9.5 rejects ComfyUI image URLs causing 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by absolutewebdev** [open-webui/open-webui#25095]
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I have also searched in the CLOSED issues AND CLOSED discussions and found no related items (your issue might already be addressed on the development branch!).
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.9.5

### Ollama Version (if applicable)

0.24.0

### Operating System

Windows 11

### Browser (if applicable)

Firefox

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

Expected behavior:

After ComfyUI successfully generates the image, Open WebUI should:

1. Accept the returned image URL from ComfyUI.
2. Fetch the generated image successfully.
3. Detect the image MIME/content type correctly.
4. Upload/store the image internally.
5. Display the generated image in the chat response.

The image generation process itself succeeds in ComfyUI. The failure occurs only when Open WebUI attempts to validate/fetch/process the returned image URL.

### Actual Behavior

Actual behavior:

1. Open WebUI successfully connects to ComfyUI.
2. ComfyUI successfully generates the image.
3. Open WebUI receives the generated image URL from ComfyUI.
4. Open WebUI rejects the image URL during validate_url().
5. get_image_data() fails and content_type becomes None.
6. Open WebUI crashes during mimetypes.guess_extension(content_type) with:

AttributeError: 'NoneType' object has no attribute 'lower'

The image is successfully generated in ComfyUI, but Open WebUI fails to fetch/process/display the generated image afterward.

### Steps to Reproduce

Steps to reproduce:

1. Install Open WebUI v0.9.5 using Docker.
2. Configure image generation backend as ComfyUI.
3. Configure ComfyUI Base URL as:

   * http://host.docker.internal:8188/
     OR
   * http://192.168.1.25:8188/
4. Use a standard ComfyUI workflow with:

   * CheckpointLoaderSimple
   * KSampler
   * CLIPTextEncode
   * VAEDecode
   * SaveImage
5. Configure workflow node mappings in Open WebUI:

   * text → 6
   * ckpt_name → 4
   * width → 5
   * height → 5
   * steps → 3
   * seed → 3
6. Generate an image from chat using:
   "Generate an image of clouds with sunlight"

Observed behavior:

* ComfyUI successfully generates the image.
* Open WebUI receives the generated image URL.
* Open WebUI rejects the returned URL as invalid inside validate_url().
* Then content_type becomes None.
* Then mimetypes.guess_extension(content_type) crashes with:
  AttributeError: 'NoneType' object has no attribute 'lower'

Relevant URL returned by ComfyUI:
http://host.docker.internal:8188/view?filename=openwebui_test_00009_.png&subfolder=&type=output

Additional notes:

* The issue started immediately after updating to v0.9.5.
* The same setup previously worked.
* ComfyUI itself works correctly and generates images successfully.
* The failure appears isolated to Open WebUI image URL validation/fetching.

### Logs & Screenshots

PS C:\Windows\system32> docker logs open-webui --tail 200
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /usr/local/lib/python3.11/site-packages/uvicorn/server.py:79> wai...
           │    │     └ <cyfunction Loop.run_until_complete at 0x7e96adf2dfc0>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7e96ae3b6310>

  File "/app/backend/open_webui/main.py", line 1997, in process_chat
    return await process_chat_response(response, ctx)
                 │                     │         └ {'request': <starlette.requests.Request object at 0x7e95b42acc10>, 'form_data': {'stream': True, 'model': 'qwen2.5:7b', 'meta...
                 │                     └ <starlette.responses.StreamingResponse object at 0x7e95b4715210>
                 └ <function process_chat_response at 0x7e95be949bc0>

  File "/app/backend/open_webui/utils/middleware.py", line 5204, in process_chat_response
    return await streaming_chat_response_handler(response, ctx)
                 │                               │         └ {'request': <starlette.requests.Request object at 0x7e95b42acc10>, 'form_data': {'stream': True, 'model': 'qwen2.5:7b', 'meta...
                 │                               └ <starlette.responses.StreamingResponse object at 0x7e95b4715210>
                 └ <function streaming_chat_response_handler at 0x7e95be949b20>

  File "/app/backend/open_webui/utils/middleware.py", line 5152, in streaming_chat_response_handler
    return await response_handler(response, events)
                 │                │         └ []
                 │                └ <starlette.responses.StreamingResponse object at 0x7e95b4715210>
                 └ <function streaming_chat_response_handler.<locals>.response_handler at 0x7e95b432dbc0>

  File "/app/backend/open_webui/utils/middleware.py", line 4599, in response_handler
    tool_result = await tool_function(**tool_function_params)
                        │               └ {'prompt': 'an image of clouds with the sun shining through them'}
                        └ <function generate_image at 0x7e95b432eac0>

  File "/app/backend/open_webui/utils/tools.py", line 136, in new_function
    return await partial_func(*args, **kwargs)
                 │             │       └ {'prompt': 'an image of clouds with the sun shining through them'}
                 │             └ ()
                 └ functools.partial(<function generate_image at 0x7e95beaedc60>, __request__=<starlette.requests.Request object at 0x7e95b42acc...

  File "/app/backend/open_webui/tools/builtin.py", line 280, in generate_image
    images = await image_generations(
                   └ <function image_generations at 0x7e95bf682a20>

  File "/app/backend/open_webui/routers/images.py", line 713, in image_generations
    image_data, content_type = await get_image_data(image['url'], headers)
                                     │              │             └ None
                                     │              └ {'url': 'http://host.docker.internal:8188/view?filename=openwebui_test_00009_.png&subfolder=&type=output'}
                                     └ <function get_image_data at 0x7e95bf682520>

> File "/app/backend/open_webui/routers/images.py", line 446, in get_image_data
    validate_url(data)
    │            └ 'http://host.docker.internal:8188/view?filename=openwebui_test_00009_.png&subfolder=&type=output'
    └ <function validate_url at 0x7e966df7f100>

  File "/app/backend/open_webui/retrieval/web/utils.py", line 103, in validate_url
    raise ValueError(ERROR_MESSAGES.INVALID_URL)
                     │              └ <ERROR_MESSAGES.INVALID_URL: 'Oops! The URL you provided is invalid. Please double-check and try again.'>
                     └ <enum 'ERROR_MESSAGES'>

ValueError: Oops! The URL you provided is invalid. Please double-check and try again.
2026-05-26 21:00:02.191 | ERROR    | open_webui.tools.builtin:generate_image:321 - generate_image error: 400: [ERROR: 'NoneType' object has no attribute 'lower']
Traceback (most recent call last):

  File "/app/backend/open_webui/routers/images.py", line 714, in image_generations
    _, url = await upload_image(
                   └ <function upload_image at 0x7e95bf682980>

  File "/app/backend/open_webui/routers/images.py", line 475, in upload_image
    image_format = mimetypes.guess_extension(content_type)
                   │         │               └ None
                   │         └ <function guess_extension at 0x7e96adb35c60>
                   └ <module 'mimetypes' from '/usr/local/lib/python3.11/mimetypes.py'>

  File "/usr/local/lib/python3.11/mimetypes.py", line 347, in guess_extension
    return _db.guess_extension(type, strict)
           │   │               │     └ True
           │   │               └ None
           │   └ <function MimeTypes.guess_extension at 0x7e96adb358a0>
           └ <mimetypes.MimeTypes object at 0x7e95bc1516d0>
  File "/usr/local/lib/python3.11/mimetypes.py", line 202, in guess_extension
    extensions = self.guess_all_extensions(type, strict)
                 │    │                    │     └ True
                 │    │                    └ None
                 │    └ <function MimeTypes.guess_all_extensions at 0x7e96adb35800>
                 └ <mimetypes.MimeTypes object at 0x7e95bc1516d0>
  File "/usr/local/lib/python3.11/mimetypes.py", line 181, in guess_all_extensions
    type = type.lower()
           └ None

AttributeError: 'NoneType' object has no attribute 'lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
    │       └ <Command main>
    └ <module 'uvicorn' from '/usr/local/lib/python3.11/site-packages/uvicorn/__init__.py'>
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1514, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function Command.main at 0x7e96ae40b1a0>
           └ <Command main>
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1435, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7e96ae511b50>
         │    └ <function Command.invoke at 0x7e96ae40ae80>
         └ <Command main>
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1298, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'host': '0.0.0.0', 'port': 8080, 'forwarded_allow_ips': '*', 'workers': 1, 'app': 'open_webui.main:app', 'uds': None, 'fd': ...
           │   │      │    │           └ <click.core.Context object at 0x7e96ae511b50>
           │   │      │    └ <function main at 0x7e96ae207ba0>
           │   │      └ <Command main>
           │   └ <function Context.invoke at 0x7e96ae40a0c0>
           └ <click.core.Context object at 0x7e96ae511b50>
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 853, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'host': '0.0.0.0', 'port': 8080, 'forwarded_allow_ips': '*', 'workers': 1, 'app': 'open_webui.main:app', 'uds': None, 'fd': ...
           │         └ ()
           └ <function main at 0x7e96ae207ba0>
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 433, in main
    run(
    └ <function run at 0x7e96ae2a5c60>
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 606, in run
    server.run()
    │      └ <function Server.run at 0x7e96ae2a54e0>
    └ <uvicorn.server.Server object at 0x7e96ae720950>
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 75, in run
    return asyncio_run(self.serve(sockets=sockets), loop_factory=self.config.get_loop_factory())
           │           │    │             │                      │    │      └ <function Config.get_loop_factory at 0x7e96ae3d05e0>
           │           │    │             │                      │    └ <uvicorn.config.Config object at 0x7e96af130e50>
           │           │    │             │                      └ <uvicorn.server.Server object at 0x7e96ae720950>
           │           │    │             └ None
           │           │    └ <function Server.serve at 0x7e96ae2a5580>
           │           └ <uvicorn.server.Server object at 0x7e96ae720950>
           └ <function asyncio_run at 0x7e96ae40e160>
  File "/usr/local/lib/python3.11/site-packages/uvicorn/_compat.py", line 30, in asyncio_run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7e96ae16b1f0>
           │      └ <function Runner.run at 0x7e96ae65cf40>
           └ <asyncio.runners.Runner object at 0x7e96ae3b6310>
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /usr/local/lib/python3.11/site-packages/uvicorn/server.py:79> wai...
           │    │     └ <cyfunction Loop.run_until_complete at 0x7e96adf2dfc0>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7e96ae3b6310>

  File "/app/backend/open_webui/main.py", line 1997, in process_chat
    return await process_chat_response(response, ctx)
                 │                     │         └ {'request': <starlette.requests.Request object at 0x7e95b42acc10>, 'form_data': {'stream': True, 'model': 'qwen2.5:7b', 'meta...
                 │                     └ <starlette.responses.StreamingResponse object at 0x7e95b4715210>
                 └ <function process_chat_response at 0x7e95be949bc0>

  File "/app/backend/open_webui/utils/middleware.py", line 5204, in process_chat_response
    return await streaming_chat_response_handler(response, ctx)
                 │                               │         └ {'request': <starlette.requests.Request object at 0x7e95b42acc10>, 'form_data': {'stream': True, 'model': 'qwen2.5:7b', 'meta...
                 │                               └ <starlette.responses.StreamingResponse object at 0x7e95b4715210>
                 └ <function streaming_chat_response_handler at 0x7e95be949b20>

  File "/app/backend/open_webui/utils/middleware.py", line 5152, in streaming_chat_response_handler
    return await response_handler(response, events)
                 │                │         └ []
                 │                └ <starlette.responses.StreamingResponse object at 0x7e95b4715210>
                 └ <function streaming_chat_response_handler.<locals>.response_handler at 0x7e95b432dbc0>

  File "/app/backend/open_webui/utils/middleware.py", line 4599, in response_handler
    tool_result = await tool_function(**tool_function_params)
                        │               └ {'prompt': 'an image of clouds with the sun shining through them'}
                        └ <function generate_image at 0x7e95b432eac0>

  File "/app/backend/open_webui/utils/tools.py", line 136, in new_function
    return await partial_func(*args, **kwargs)
                 │             │       └ {'prompt': 'an image of clouds with the sun shining through them'}
                 │             └ ()
                 └ functools.partial(<function generate_image at 0x7e95beaedc60>, __request__=<starlette.requests.Request object at 0x7e95b42acc...

> File "/app/backend/open_webui/tools/builtin.py", line 280, in generate_image
    images = await image_generations(
                   └ <function image_generations at 0x7e95bf682a20>

  File "/app/backend/open_webui/routers/images.py", line 773, in image_generations
    raise HTTPException(status_code=400, detail=ERROR_MESSAGES.DEFAULT(error))
          │                                     │              │       └ AttributeError("'NoneType' object has no attribute 'lower'")
          │                                     │              └ <function ERROR_MESSAGES.<lambda> at 0x7e96aa320ae0>
          │                                     └ <enum 'ERROR_MESSAGES'>
          └ <class 'fastapi.exceptions.HTTPException'>

fastapi.exceptions.HTTPException: 400: [ERROR: 'NoneType' object has no attribute 'lower']
2026-05-26 21:00:02.999 | INFO     | open_webui.utils.images.comfyui:comfyui_create_image:204 - WebSocket connection established.
2026-05-26 21:00:03.000 | INFO     | open_webui.utils.images.comfyui:comfyui_create_image:205 - Sending workflow to WebSocket server.
2026-05-26 21:00:03.000 | INFO     | open_webui.utils.images.comfyui:comfyui_create_image:206 - Workflow: {'3': {'inputs': {'seed': 886721234991751, 'steps': 30, 'cfg': 7, 'sampler_name': 'euler', 'scheduler': 'normal', 'denoise': 1, 'model': ['4', 0], 'positive': ['6', 0], 'negative': ['7', 0], 'latent_image': ['5', 0]}, 'class_type': 'KSampler'}, '4': {'inputs': {'ckpt_name': 'juggernautXL_ragnarokBy.safetensors'}, 'class_type': 'CheckpointLoaderSimple'}, '5': {'inputs': {'width': 1024, 'height': 1024, 'batch_size': 1}, 'class_type': 'EmptyLatentImage'}, '6': {'inputs': {'text': 'an image of clouds with the sun shining through them', 'clip': ['4', 1]}, 'class_type': 'CLIPTextEncode'}, '7': {'inputs': {'text': 'blurry, low quality, watermark, text, distorted', 'clip': ['4', 1]}, 'class_type': 'CLIPTextEncode'}, '8': {'inputs': {'samples': ['3', 0], 'vae': ['4', 2]}, 'class_type': 'VAEDecode'}, '9': {'inputs': {'filename_prefix': 'openwebui_test', 'images': ['8', 0]}, 'class_type': 'SaveImage'}}
2026-05-26 21:00:03.000 | INFO     | open_webui.utils.images.comfyui:queue_prompt:19 - queue_prompt
2026-05-26 21:00:07.683 | WARNING  | open_webui.utils.middleware:response_handler:5111 - Task was cancelled!
2026-05-26 21:00:07.693 | INFO     | open_webui.main:process_chat:1999 - Chat processing was cancelled
2026-05-26 21:00:07.694 | INFO     | uvicorn.protocols.http.httptools_impl:send:483 - 172.17.0.1:59440 - "POST /api/tasks/chat/f2ddc6c9-fe66-4c09-b9d3-1a141d5b5032/stop HTTP/1.1" 200
2026-05-26 21:00:09.427 | INFO     | uvicorn.protocols.http.httptools_impl:send:483 - 172.17.0.1:59440 - "GET /_app/version.json HTTP/1.1" 304
PS C:\Windows\system32>

### Additional Information

This may be related to:

issue #24565 ("edit_image with ComfyUI no longer returns images in 0.9.5")
earlier ComfyUI integration regressions such as #4328 and #16799

The traceback indicates validate_url() is rejecting valid ComfyUI-generated image URLs returned from:
http://host.docker.internal:8188/view?...

----------- Actual output in chat -----------

qwen2.5:7b

View Result from generate_image 
 
Input 
prompt 
an image of clouds with the sun shining through them
 
Output
{
  "error": "400: [ERROR: 'NoneType' object has no attribute 'lower']"
}

It seems there was an issue processing your request. Let's try that again.
  
It seems there was an issue processing your request. Let's try generating the image again with the same prompt.

**Comment by Classic298** [comment]
fixed in dev, please check for duplicates

there's a workaround for 0.9.5 deployments, which i will not post deliberately because it has security tradeoffs. do not recomment changing that config. Best to install dev (and help us test the dev branch) or wait for next version
