### ISSUE TITLE
Bug: 'Depends' object has no attribute 'role'

### ISSUE THREAD

**Issue by brantje** [open-webui/open-webui#6483]
# Bug Report

## Important Notes

- **Before submitting a bug report**: Please check the Issues or Discussions section to see if a similar issue or feature request has already been posted. It's likely we're already tracking it! If you’re unsure, start a discussion post first. This will help us efficiently focus on improving the project.

- **Collaborate respectfully**: We value a constructive attitude, so please be mindful of your communication. If negativity is part of your approach, our capacity to engage may be limited. We’re here to help if you’re open to learning and communicating positively. Remember, Open WebUI is a volunteer-driven project managed by a single maintainer and supported by contributors who also have full-time jobs. We appreciate your time and ask that you respect ours.

- **Contributing**: If you encounter an issue, we highly encourage you to submit a pull request or fork the project. We actively work to prevent contributor burnout to maintain the quality and continuity of Open WebUI.

- **Bug reproducibility**: If a bug cannot be reproduced with a `:main` or `:dev` Docker setup, or a pip install with Python 3.11, it may require additional help from the community. In such cases, we will move it to the "issues" Discussions section due to our limited resources. We encourage the community to assist with these issues. Remember, it’s not that the issue doesn’t exist; we need your help!

Note: Please remove the notes above when submitting your post. Thank you for your understanding and support!

---

## Installation Method
Docker

## Environment

- **Open WebUI Version:** 0.3.35
- **Ollama (if applicable):** [e.g., v0.2.0, v0.1.32-rc1]

- **Operating System:** Ubuntu 24.04
- **Browser (if applicable):** Firefox

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
Script should run fine

## Actual Behavior:
After updating to 0.3.35 (from 0.3.33), the script crashes with the following error:
```
Uh-oh! There was an issue connecting to mcts mistral-nemo:12b.
'Depends' object has no attribute 'role'
```

## Description
After upgrading from 0.3.33 to 0.3.35, the script crashes with an error it can't find the attribute role.

**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details

**Steps to Reproduce:**
Download the function: https://github.com/av/harbor/blob/main/open-webui/extras/mcts.py
Open a chat with a mcts model.
Type something

## Logs and Screenshots

**Browser Console Logs:**
```
Object { error: {…} }
[index.ts:63:11](https://chat.bytelab.sh/src/lib/apis/streaming/index.ts)
Object { detail: "'Depends' object has no attribute 'role'" }
[Chat.svelte:1756:10](https://chat.bytelab.sh/src/lib/components/chat/Chat.svelte)
TypeError: e.choices is undefined
    T index.ts:245
[Chat.svelte:1904:13](https://chat.bytelab.sh/src/lib/components/chat/Chat.svelte)
Failed to parse response:  TypeError: e.choices is undefined
    S index.ts:287
[index.ts:315:10](https://chat.bytelab.sh/src/lib/apis/index.ts)
Array []
[Chat.svelte:1951:11](https://chat.bytelab.sh/src/lib/components/chat/Chat.svelte)
```
​
**Docker Container Logs:**
``` 
INFO:     172.70.47.114:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
generate_title
visual_tree_of_thoughts.mcts-mistral-nemo:12b
visual_tree_of_thoughts
visual_tree_of_thoughts
Error: 'Depends' object has no attribute 'role'
INFO:     172.70.47.114:0 - "POST /api/task/title/completions HTTP/1.1" 200 OK
INFO:     172.70.47.114:0 - "POST /api/v1/chats/9bcaedb4-868d-4580-8d81-45aea9e18a0c HTTP/1.1" 200 OK
INFO:     172.70.47.114:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
INFO:     172.70.47.114:0 - "GET /api/v1/chats/9bcaedb4-868d-4580-8d81-45aea9e18a0c/tags HTTP/1.1" 200 OK
2024-10-27 19:22:51,021 - function_visual_tree_of_thoughts - DEBUG - Pipe mcts received: {'model': 'visual_tree_of_thoughts.mcts-mistral-nemo:12b', 'messages': [{'role': 'user', 'content': '### Task:\nGenerate 1-3 broad tags categorizing the main themes of the chat history, along with 1-3 more specific subtopic tags.\n\n### Guidelines:\n- Start with high-level domains (e.g. Science, Technology, Philosophy, Arts, Politics, Business, Health, Sports, Entertainment, Education)\n- Consider including relevant subfields/subdomains if they are strongly represented throughout the conversation\n- If content is too short (less than 3 messages) or too diverse, use only ["General"]\n- Use the chat\'s primary language; default to English if multilingual\n- Prioritize accuracy over specificity\n\n### Output:\nJSON format: { "tags": ["tag1", "tag2", "tag3"] }\n\n### Chat History:\n<chat_history>\nUSER: Three playing cards in a row. Can you name them with these clues? There is a two to the right of a king. A diamond will be found to the left of a spade. An ace is to the left of a heart. A heart is to the left of a spade. Now, identify all three cards.\nASSISTANT: \n</chat_history>'}], 'stream': False}
2024-10-27 19:22:51,021 - function_visual_tree_of_thoughts - DEBUG - Question: ### Task:
Generate 1-3 broad tags categorizing the main themes of the chat history, along with 1-3 more specific subtopic 7ags.

### Guidelines:
- Start with high-level domains (e.g. Science, Technology, Philosophy, Arts, Politics, Business, Health, Sports, Entertainment, Education)
- Consider including relevant subfields/subdomains if they are strongly represented throughout the conversation
- If content is too short (less than 3 messages) or too diverse, use only ["General"]
- Use the chat's primary language; default to English if multilingual
- Prioritize accuracy over specificity

### Output:
JSON format: { "tags": ["tag1", "tag2", "tag3"] }

### Chat History:
<chat_history>
USER: Three playing cards in a row. Can you name them with these clues? There is a two to the right of a king. A diamond will be found to the left of a spade. An ace is to the left of a heart. A heart is to the left of a spade. Now, identify all three cards.
ASSISTANT:
</chat_history>
2024-10-27 19:22:51,021 - function_visual_tree_of_thoughts - DEBUG - Progress: Preparing initial thoughts...
generate_chat_tags
visual_tree_of_thoughts.mcts-mistral-nemo:12b
content ### Task:
Generate 1-3 broad tags categorizing the main themes of the chat history, along with 1-3 more specific subtopic tags.

### Guidelines:
- Start with high-level domains (e.g. Science, Technology, Philosophy, Arts, Politics, Business, Health, Sports, Entertainment, Education)
- Consider including relevant subfields/subdomains if they are strongly represented throughout the conversation
- If content is too short (less than 3 messages) or too diverse, use only ["General"]
- Use the chat's primary language; default to English if multilingual
- Prioritize accuracy over specificity

### Output:
JSON format: { "tags": ["tag1", "tag2", "tag3"] }

### Chat History:
<chat_history>
USER: Three playing cards in a row. Can you name them with these clues? There is a two to the right of a king. A diamond will be found to the left of a spade. An ace is to the left of a heart. A heart is to the left of a spade. Now, identify all three cards.
ASSISTANT:
</chat_history>
visual_tree_of_thoughts
visual_tree_of_thoughts
Error: 'NoneType' object is not callable
INFO:     172.70.47.114:0 - "POST /api/task/tags/completions HTTP/1.1" 200 OK
```

## Additional Information

Did something change in the API's? I'll be glad to fix this script and send a PR to harbor.
