### ISSUE TITLE
issue:

### ISSUE THREAD

**Issue by matthew777777** [open-webui/open-webui#12504]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Other

### Open WebUI Version

v0.6.1

### Operating System

Mac OS 

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

Web Search was working on 0.6 before update from yesterday.

### Actual Behavior

When using search it should work but it there an issue.

It seems that embedding_function is None, and the code tries to call .encode() on it — but you can’t call a method on None.

### Steps to Reproduce

Run open web ui with uv with python3.11 or pip and set up google pse or use duckduckgo and it will fail.

### Logs & Screenshots

, World | Latest News & Updates | BBC News web-search-f8be51190f325e8a64c55e0867d3acb39a0392c12e819f0b2ddf - {}
2025-04-06 11:22:07.063 | INFO     | open_webui.routers.retrieval:save_docs_to_vector_db:894 - adding to collection web-search-f8be51190f325e8a64c55e0867d3acb39a0392c12e819f0b2ddf - {}
2025-04-06 11:22:07.063 | ERROR    | open_webui.routers.retrieval:save_docs_to_vector_db:935 - 'NoneType' object has no attribute 'encode' - {}
Traceback (most recent call last):

  File "/Users/monikamalinowska/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x100982d40>
    └ <WorkerThread(AnyIO worker thread, started 13347024896)>
  File "/Users/monikamalinowska/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x31870aa20>
    └ <WorkerThread(AnyIO worker thread, started 13347024896)>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function save_docs_to_vector_db at 0x301607f60>, <starlette.requests.Request object at 0x31a7d24d0>, [Docu...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x318259a80>
> File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/routers/retrieval.py", line 912, in save_docs_to_vector_db
    embeddings = embedding_function(
                 └ <function get_embedding_function.<locals>.<lambda> at 0x31a811800>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/retrieval/utils.py", line 359, in <lambda>
    return lambda query, prefix=None, user=None: embedding_function.encode(
                  │                              └ None
                  └ ['World | Latest News & Updates | BBC NewsSkip to contentBritish Broadcasting CorporationHomeNewsSportBusinessInnovationCultu...

AttributeError: 'NoneType' object has no attribute 'encode'
2025-04-06 11:22:07.068 | ERROR    | open_webui.routers.retrieval:process_web_search:1513 - 'NoneType' object has no attribute 'encode' - {}
Traceback (most recent call last):

  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/bin/open-webui", line 12, in <module>
    sys.exit(app())
    │   │    └ <typer.main.Typer object at 0x10099e350>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/typer/main.py", line 322, in __call__
    return get_command(self)(*args, **kwargs)
           │           │      │       └ {}
           │           │      └ ()
           │           └ <typer.main.Typer object at 0x10099e350>
           └ <function get_command at 0x101557740>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function TyperGroup.main at 0x101555bc0>
           └ <TyperGroup >
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/typer/core.py", line 740, in main
    return _main(
           └ <function _main at 0x101554e00>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/typer/core.py", line 195, in _main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x102c9f690>
         │    └ <function MultiCommand.invoke at 0x100c91300>
         └ <TyperGroup >
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x101337990>
           │               │       │       └ <function Command.invoke at 0x100c90cc0>
           │               │       └ <TyperCommand serve>
           │               └ <click.core.Context object at 0x101337990>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x1019f2980>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'host': '0.0.0.0', 'port': 8080}
           │   │      │    │           └ <click.core.Context object at 0x101337990>
           │   │      │    └ <function serve at 0x1019f2840>
           │   │      └ <TyperCommand serve>
           │   └ <function Context.invoke at 0x100c07600>
           └ <click.core.Context object at 0x101337990>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'host': '0.0.0.0', 'port': 8080}
                       └ ()
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/typer/main.py", line 697, in wrapper
    return callback(**use_params)
           │          └ {'host': '0.0.0.0', 'port': 8080}
           └ <function serve at 0x101859120>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/__init__.py", line 77, in serve
    uvicorn.run(open_webui.main.app, host=host, port=port, forwarded_allow_ips="*")
    │       │   │          │    │         │          └ 8080
    │       │   │          │    │         └ '0.0.0.0'
    │       │   │          │    └ <fastapi.applications.FastAPI object at 0x301f461d0>
    │       │   │          └ <module 'open_webui.main' from '/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packag...
    │       │   └ <module 'open_webui' from '/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/op...
    │       └ <function run at 0x101858680>
    └ <module 'uvicorn' from '/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/uvico...
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/uvicorn/main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x1018589a0>
    └ <uvicorn.server.Server object at 0x318016850>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x101858a40>
           │       │   └ <uvicorn.server.Server object at 0x318016850>
           │       └ <function run at 0x101635760>
           └ <module 'asyncio' from '/Users/monikamalinowska/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyn...
  File "/Users/monikamalinowska/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x1016ea020>
           │      └ <function Runner.run at 0x101659c60>
           └ <asyncio.runners.Runner object at 0x317c0b890>
  File "/Users/monikamalinowska/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG...
           │    │     └ <cyfunction Loop.run_until_complete at 0x3180568e0>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x317c0b890>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
          │    │   │      │                      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x31a7cca40>
          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x31a7ce200>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8080), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x317d04c90>
          └ <open_webui.main.RedirectMiddleware object at 0x317558190>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x31a7cca40>
          │                            │    │    │     │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x31a7ce200>
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8080), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x31a7d07d0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x303cbff90>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x317d04c90>
          └ <function wrap_app_handling_exceptions at 0x110640c20>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x31a7cc860>
          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x31a7ce200>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8080), 'cl...
          └ <fastapi.routing.APIRouter object at 0x303cbff90>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x31a7cc860>
          │    │                │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x31a7ce200>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8080), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x303cbff90>>
          └ <fastapi.routing.APIRouter object at 0x303cbff90>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x31a7cc860>
          │     │      │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x31a7ce200>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8080), 'cl...
          │     └ <function Route.handle at 0x110642160>
          └ APIRoute(path='/api/chat/completions', name='chat_completion', methods=['POST'])
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x31a7cc860>
          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x31a7ce200>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8080), 'cl...
          │    └ <function request_response.<locals>.app at 0x317e72020>
          └ APIRoute(path='/api/chat/completions', name='chat_completion', methods=['POST'])
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x31a7cc860>
          │                            │    │        │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x31a7ce200>
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8080), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x31a7d24d0>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x31a7ccfe0>
          └ <function wrap_app_handling_exceptions at 0x110640c20>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x31a7cce00>
          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x31a7ce200>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8080), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x31a7ccfe0>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x31a7d24d0>
                     └ <function get_request_handler.<locals>.app at 0x317cf4a40>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x110643f60>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user': UserModel(id='36b87bdd-b950-4ccb-abb4-fd37b9c5e1a1', name='Matthew', email='new.matthew@tutanota.com', role='admin',...
                 │         └ <function chat_completion at 0x317ee19e0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/main.py", line 1105, in chat_completion
    form_data, metadata, events = await process_chat_payload(
    │          │                        └ <function process_chat_payload at 0x303b5c180>
    │          └ {'user_id': '36b87bdd-b950-4ccb-abb4-fd37b9c5e1a1', 'chat_id': '84440fb8-9736-4376-b978-5a7f6404cc70', 'message_id': 'dc209e2...
    └ {'stream': True, 'model': 'llama3.2:latest', 'messages': [{'role': 'system', 'content': 'Perform the task to the best of your...
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/utils/middleware.py", line 785, in process_chat_payload
    form_data = await chat_web_search_handler(
                      └ <function chat_web_search_handler at 0x303bba700>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/utils/middleware.py", line 388, in chat_web_search_handler
    results = await process_web_search(
                    └ <function process_web_search at 0x30164db20>
> File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/routers/retrieval.py", line 1497, in process_web_search
    await run_in_threadpool(
          └ <function run_in_threadpool at 0x11001b9c0>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
                 │     │         │        └ functools.partial(<function save_docs_to_vector_db at 0x301607f60>, <starlette.requests.Request object at 0x31a7d24d0>, [Docu...
                 │     │         └ <function run_sync at 0x1018b1f80>
                 │     └ <module 'anyio.to_thread' from '/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packag...
                 └ <module 'anyio' from '/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/_...
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
                 └ <function get_async_backend at 0x1018b1080>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
                 └ <Future finished exception=AttributeError("'NoneType' object has no attribute 'encode'")>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/routers/retrieval.py", line 936, in save_docs_to_vector_db
    raise e
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/routers/retrieval.py", line 912, in save_docs_to_vector_db
    embeddings = embedding_function(
                 └ <function get_embedding_function.<locals>.<lambda> at 0x31a811800>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/retrieval/utils.py", line 359, in <lambda>
    return lambda query, prefix=None, user=None: embedding_function.encode(
                  │                              └ None
                  └ ['World | Latest News & Updates | BBC NewsSkip to contentBritish Broadcasting CorporationHomeNewsSportBusinessInnovationCultu...

AttributeError: 'NoneType' object has no attribute 'encode'
2025-04-06 11:22:07.078 | ERROR    | open_webui.utils.middleware:chat_web_search_handler:423 - 400: [ERROR: 'NoneType' object has no attribute 'encode'] - {}
Traceback (most recent call last):

  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/routers/retrieval.py", line 1497, in process_web_search
    await run_in_threadpool(
          └ <function run_in_threadpool at 0x11001b9c0>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
                 │     │         │        └ functools.partial(<function save_docs_to_vector_db at 0x301607f60>, <starlette.requests.Request object at 0x31a7d24d0>, [Docu...
                 │     │         └ <function run_sync at 0x1018b1f80>
                 │     └ <module 'anyio.to_thread' from '/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packag...
                 └ <module 'anyio' from '/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/_...
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
                 └ <function get_async_backend at 0x1018b1080>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
                 └ <Future finished exception=AttributeError("'NoneType' object has no attribute 'encode'")>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/routers/retrieval.py", line 936, in save_docs_to_vector_db
    raise e
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/routers/retrieval.py", line 912, in save_docs_to_vector_db
    embeddings = embedding_function(
                 └ <function get_embedding_function.<locals>.<lambda> at 0x31a811800>
  File "/Users/monikamalinowska/.cache/uv/archive-v0/xficOnuRC9iZH1NvQTQG0/lib/python3.11/site-packages/open_webui/retrieval/utils.py", line 359, in <lambda>
    return lambda query, prefix=None, user=None: embedding_function.encode(
                  │                              └ None
                  └ ['World | Latest News & Updates | BBC NewsSkip to contentBritish Broadcasting CorporationHomeNewsSportBusinessInnovationCultu...

AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

**Comment by dl4rce** [comment]
Same issue here.

**Comment by spammenotinoz** [comment]
Check your embeddings config
