### ISSUE TITLE
Model system prompts not being templated

### ISSUE THREAD

**Issue by ProjectMoon** [open-webui/open-webui#9386]
# Bug Report

## Installation Method

Docekr

## Environment

- **Open WebUI Version:** 0.5.8
- **Ollama (if applicable):** 0.5.7

- **Operating System:** Gentoo Liunx
- **Browser (if applicable):** Firefox 135

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Templating of variables in system prompts to work.

## Actual Behavior:

Templating of variables does not seem to occur when using the regular (non-native) tool calling.

## Description

**Bug Summary:**
If a model has a variable in its system prompt like `{{USER_LOCATION}}`, this should be replaced by the variable name. But it seems that in 0.5.8, the templating is not happening. I saw this by the OSM tool searching for stores near `{{USER_LOCATION}}` instead of an address or a GPS coordinate.

**Docker Container Logs:**

This is a tiny bit of the container log, which includes the output from the OSM tool:
```
apply_model_system_prompt_to_body: metadata {'task': 'function_calling'}
[OSM] Searching for [groceries] (shop=supermarket, etc) near place: {{USER_LOCATION}}
[OSM] Searching Nominatim for: {{USER_LOCATION}}
```

## Additional Information

The model's system prompt is something like `The user's location is: {{USER_LOCATION}}`.

Native tool calling could not be tested. This was tested only with default function calling.

**Comment by thiswillbeyourgithub** [comment]
This might be due to an error I'm getting since updating from 0.5.7 to 0.5.9 : I get `'UserModel' object has no attribute 'get'` and the latest error log I get until that is: `apply_model_system_prompt_to_body: metadata id=XXX etc`

This indicates to me that both errors are probably around those functions:
https://github.com/open-webui/open-webui/blob/ab94468ffa765c9ed169cff3a7caa18e85f434db/backend/open_webui/utils/payload.py#L10

https://github.com/open-webui/open-webui/blob/ab94468ffa765c9ed169cff3a7caa18e85f434db/backend/open_webui/utils/task.py#L35


Open-WebUI is unusable in this state so I'll try rolling back to 0.5.7

**Comment by oatmealm** [comment]
Can confirm. It works when I remove the models system prompt. Hope this is a regression and not by design. One of the coolest features of OWUI.

**Comment by Yppiti** [comment]
Also chiming in that removing system prompts fixes the interaction with API but it's useless in this state. Using a custom model was the main reason for using system prompts. Downgrading to temporarily fix this. Not usable in this state, unfortunately.

**Comment by IgorFZ** [comment]
When attempting to use a custom model, such as Google's Gemini 1.5 Flash Latest, to perform a RAG (Retrieval Augmented Generation) with a custom prompt, the following error occurred:

```python
'usermodel' object has no attribute 'get'
```

This error did not occur after removing the prompt from the model.

**Comment by oatmealm** [comment]
No running into issue with the embedding function. Downgrading since it's a mess at this stage.

**Comment by tjbck** [comment]
Addressed with ff84c120f5260e7b40cc31b9f60a2afe8ba9e3c8, 0.5.10 will be released shortly
