### ISSUE TITLE
Prompt with {[CLIPBOARD}} not working in Firefox

### ISSUE THREAD

**Issue by btzs** [open-webui/open-webui#1658]
# Bug Report

## Description

**Bug Summary:**
I set up a prompt including the ``{{CLIPBOARD}}`` tag to automatically include the clipboard. It works on Edge but not on Firefox. On Edge a dialogue opens to to ask for clipboard permission. On Firefox no such dialogue appears.

**Steps to Reproduce:**
1. Create normal prompt without ``{{CLIPBOARD}}`` and use it --> no problem
2. add ``{{CLIPBOARD}}`` to prompt --> prompt not working anymore. 
3. error in console

**Expected Behavior:**
- Prompt should be inserted into prompt field with {{CLIPBOARD}} getting replaced by the actual content of the clipboard. 
or:
- Warning that function is not supported on Firefox (

**Actual Behavior:**
Nothing happens.

## Environment

- **Open WebUI Version:** v0.1.119

- **Ollama (if applicable):** -

- **Operating System:** Windows 10
- **Browser (if applicable):** 
- not working on Firefox: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
- working on Edge: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0

## Reproduction Details
**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [xI am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
```
Uncaught (in promise) TypeError: navigator.clipboard.readText is not a function
    Immutable 50
    <anonymous> https://owui.btzs.eu/:70
    promise callback* https://owui.btzs.eu/:69

```

**Docker Container Logs:**
-

## Installation Method

Docker
