### ISSUE TITLE
JSON log sink crashes with AttributeError on every exception (LOG_FORMAT=json)

### ISSUE THREAD

**Issue by cflocke-codecentric** [open-webui/open-webui#25135]
## Summary

With `LOG_FORMAT=json`, the loguru JSON sink in `backend/open_webui/utils/logger.py` crashes on every `logger.exception(...)` call. The original traceback is lost and replaced by a `--- Logging error in Loguru Handler ---` freetext block on stderr, which is not valid JSON and breaks structured-log alerting (Cloud Logging / Datadog / etc.).

## Reproduction

Set `LOG_FORMAT=json` and run:

```python
from loguru import logger
try:
    1 / 0
except Exception:
    logger.exception("boom")
```

Observed (on stderr, no JSON line on stdout):

```
--- Logging error in Loguru Handler #1 ---
Record was: ...
Traceback (most recent call last):
  File "/app/backend/open_webui/utils/logger.py", line 65, in _json_sink
    log_entry['error'] = ''.join(record['exception'].format_exception()).rstrip()
AttributeError: 'RecordException' object has no attribute 'format_exception'
--- End of logging error ---
```

## Root cause

`record['exception']` is loguru's `RecordException`, a `NamedTuple(type, value, traceback)` — it has no `.format_exception()` method.

Introduced in #21747 ("feat: add LOG_FORMAT=json for structured JSON logging"). The stdlib `JSONFormatter` added in the same PR (`backend/open_webui/env.py:98`) already does the right thing: `traceback.format_exception(*record.exc_info)`.

## Impact

Anyone running with `LOG_FORMAT=json` loses all exception tracebacks from structured logs. We hit this in production (GCP Cloud Run) — pgvector SSL disconnects and SQLAlchemy `OperationalError`s from a scheduler loop were silently swallowed for days.

## Suggested fix

Mirror `env.py:98`:

```python
log_entry['error'] = ''.join(traceback.format_exception(*record['exception'])).rstrip()
```

Happy to open a PR.

**Comment by tjbck** [comment]
Good catch, addressed in dev!
