### ISSUE TITLE
issue:"version 0.3.27-dev2 fun "Narrative Memory Filter" not work on windows"

### ISSUE THREAD

**Issue by shenyunhuan** [open-webui/open-webui#5665]
Bug Report
Installation Method
I installed the project using pip in a virtual environment.

Environment
Open WebUI Version: v0.3.27-dev2
Ollama (if applicable): Not applicable
Operating System: Windows 11
Browser (if applicable): Edge 128
Confirmation:

 I have read and followed all the instructions provided in the README.md.
 I am on the latest version of Open WebUI.
 I have included the browser console logs.
 I have included the Docker container logs (not applicable).
 I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.
Expected Behavior:
I expected the "Narrative Memory Filter" feature to work without any errors.

Actual Behavior:
The feature does not work, and I receive the following error: cannot import name 'CHROMA_CLIENT' from 'open_webui.config' (C:\Users\xxx\anaconda3\Lib\site-packages\open_webui\config.py).

Description
Bug Summary: The "Narrative Memory Filter" is not functioning in Open WebUI v0.3.27-dev2 on Windows 11.

Reproduction Details
Steps to Reproduce:

Install Open WebUI v0.3.27-dev2 using pip.
Attempt to use the "Narrative Memory Filter" feature.
Observe the error in the console.
Logs and Screenshots
Browser Console Logs:

javascript
Error: cannot import name 'CHROMA_CLIENT' from 'open_webui.config' (C:\Users\xxx\anaconda3\Lib\site-packages\open_webui\config.py)
Docker Container Logs: (Not applicable)

Screenshots/Screen Recordings (if applicable): (Not available)

Additional Information
The feature works correctly in version 0.3.21, which indicates a potential issue with the latest version.

Note
If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

Feel free to adjust any parts as needed!

**Comment by tjbck** [comment]
The function itself needs to be updated, CHROMA_CLIENT has been deprecated.

**Comment by shenyunhuan** [comment]
> The function itself needs to be updated, CHROMA_CLIENT has been deprecated.
The function cannot update
"https://openwebui.com/#open-webui-community "  "502 Bad Gateway
nginx/1.24.0 (Ubuntu)"
