### ISSUE TITLE
Persistent Image Generation Error, despite update fix: get_automatic1111_api_auth() missing 1 required positional argument: 'request'

### ISSUE THREAD

**Issue by misterjice** [open-webui/open-webui#8096]
# Bug Report

---

## Installation Method

Docker

## Environment

- **Open WebUI Version:** 0.5.1
- **Ollama (if applicable):** 0.5.4

- **Operating System:** Windows 11
- **Browser (if applicable):** Brave

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I expect to be able to connect to the automatic1111 server and generate images in OpenWebUI

## Actual Behavior:

I'm getting an error: [ERROR: get_automatic1111_api_auth() missing 1 required positional argument: 'request']
Image generation button is no longer available in chats.

## Description

**Bug Summary:**
Merry Christmas and thank you for the updates.

I cannot connect to the server even after updating to 0.5.1 in admin settings.  Also, models were not automatically generating images as they saw fit for a couple updates now. And, now, no button to generate images, which do not seem to work at all. 

Server is running and I tested it in the automatic1111 GUI in the same browser I run OpenWebUI.

## Reproduction Details

**Steps to Reproduce:**
Go to bottom-left UserName -> Settings -> Admin Settings -> Images
Toggle Image Generation (Experimental)
(sever address is same as before)
Get error pop-up: [ERROR: get_automatic1111_api_auth() missing 1 required positional argument: 'request']

## Logs and Screenshots

**Browser Console Logs:**
Backend config: Object
+layout.svelte:66 connected TJAo58L_OjLGfulxAAAV
+layout.svelte:85 user-count Object
+layout.svelte:90 usage Object
+layout.svelte:85 user-count Object
Images.svelte:204 {type: 'prompt', key: 'text', node_ids: Array(0)}
Images.svelte:204 {type: 'model', key: 'ckpt_name', node_ids: Array(0)}
Images.svelte:204 {type: 'width', key: 'width', node_ids: Array(0)}
Images.svelte:204 {type: 'height', key: 'height', node_ids: Array(0)}
Images.svelte:204 {type: 'steps', key: 'steps', node_ids: Array(0)}
Images.svelte:204 {type: 'seed', key: 'seed', node_ids: Array(0)}
index.ts:170 
        
        
       GET http://localhost:8080/api/v1/images/models 400 (Bad Request)
window.fetch @ fetcher.js:76
p @ index.ts:170
E @ Images.svelte:101
w @ Images.svelte:124
await in w
y @ Images.svelte:267
(anonymous) @ lifecycle.js:105
(anonymous) @ lifecycle.js:104
n.$$.update @ Switch.svelte:8
dt @ scheduler.js:115
_t @ scheduler.js:79
Promise.then
ut @ scheduler.js:20
ht @ Component.js:81
(anonymous) @ Component.js:139
T @ Images.svelte:244
Me @ Images.svelte:287
(anonymous) @ Component.js:138
l @ Switch.svelte:12
i @ switch-thumb.svelte:12
(anonymous) @ Component.js:138
onCheckedChange @ switch.svelte:29
(anonymous) @ overridable.js:9
f @ index.js:69
r @ overridable.js:5
r @ create.js:21
(anonymous) @ create.js:38
(anonymous) @ event.js:23
(anonymous) @ event.js:51
index.ts:183 {detail: "[ERROR: get_automatic1111_api_auth() missing 1 required positional argument: 'request']"}

**Docker Container Logs:**
2024-12-26 01:47:08 INFO:     172.17.0.1:50212 - "GET /_app/immutable/chunks/relativeTime.HIEE8cw9.js.map HTTP/1.1" 200 OK
2024-12-26 01:47:09 INFO:     172.17.0.1:50230 - "GET /api/v1/chats/4ad1eb4d-4e9f-413a-b9cc-9081c62072b5 HTTP/1.1" 200 OK
2024-12-26 01:47:28 INFO:     172.17.0.1:60772 - "GET /api/v1/images/config HTTP/1.1" 200 OK
2024-12-26 01:47:28 INFO:     172.17.0.1:60772 - "GET /api/v1/images/image/config HTTP/1.1" 200 OK
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'IMAGE_GENERATION_ENGINE' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'ENABLE_IMAGE_GENERATION' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'IMAGES_OPENAI_API_BASE_URL' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'IMAGES_OPENAI_API_KEY' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'AUTOMATIC1111_BASE_URL' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'AUTOMATIC1111_API_AUTH' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'AUTOMATIC1111_CFG_SCALE' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'AUTOMATIC1111_SAMPLER' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'AUTOMATIC1111_SCHEDULER' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'COMFYUI_BASE_URL' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'COMFYUI_WORKFLOW' to the database
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'COMFYUI_WORKFLOW' to the database
2024-12-26 01:47:32 INFO:     172.17.0.1:60772 - "POST /api/v1/images/config/update HTTP/1.1" 200 OK
2024-12-26 01:47:32 INFO:     172.17.0.1:60772 - "GET /api/config HTTP/1.1" 200 OK
2024-12-26 01:47:32 INFO  [open_webui.env] Saving 'ENABLE_IMAGE_GENERATION' to the database
2024-12-26 01:47:32 INFO:     172.17.0.1:60772 - "GET /api/v1/images/models HTTP/1.1" 400 Bad Request
2024-12-26 01:47:38 INFO:     172.17.0.1:59022 - "GET /api/v1/chats/9261668e-b0ed-462b-be2c-f302d468e789 HTTP/1.1" 200 OK

**Screenshots/Screen Recordings (if applicable):**
![Screenshot 2024-12-26 015620](https://github.com/user-attachments/assets/38a0f7a4-561e-48aa-b3cc-765b29a60f03)

## Additional Information

Seems to have trouble loading models:  2024-12-26 01:50:56 INFO:     172.17.0.1:55544 - "GET /api/v1/images/models HTTP/1.1" 400 Bad Request

Also, in the last bug report I did before the latest update, @godsey mentioned "I believe (request) needs to be added on lines 239, 357, and 581 as well."  I'm not sure if that will help but I figured I'd share.  Original post with comments here: 
 [https://github.com/open-webui/open-webui/issues/8065](url)

@tjbck said there was an additional fix; so I'm not sure if this is in a forthcoming update but I figured it is prudent to say something about this.

Thank you for your work and for making OpenWebUI!

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Were you able to try the latest main?

**Comment by misterjice** [comment]
You mean 0.5.1?

Yes, I have it installed.  Or do you mean the dev branch?  (I don't have that)

**Comment by Master-Pr0grammer** [comment]
Having same exact issue on the latest version

**Comment by tjbck** [comment]
latest version and the latest main image are two different images, try `docker pull ghcr.io/open-webui/open-webui:main` or you could try switching to the `dev` branch!

**Comment by Master-Pr0grammer** [comment]
@tjbck I should have specified, I am running the pip version, not the docker image like @ misterjice

**Comment by misterjice** [comment]
> latest version and the latest main image are two different images, try `docker pull ghcr.io/open-webui/open-webui:main` or you could try switching to the `dev` branch!

Thank you for clarifying!  I was looking into how to use watchtower to change to the main image and keep my data intact, apparently I already have it.  I set up docker using this command:

`docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
`

So, I've been using the main image all long!  So, what is the latest version?  is ghcr.io/open-webui/open-webui:latest correct?  And how does this one differ from the dev branch? (ghcr.io/open-webui/open-webui:dev)

**Comment by Master-Pr0grammer** [comment]
For context, this is the usage reported by ollama from the same model with the same prompt:
```
total duration:       600.813205ms
load duration:        22.364032ms
prompt eval count:    11 token(s)
prompt eval duration: 96ms
prompt eval rate:     114.58 tokens/s
eval count:           22 token(s)
eval duration:        481ms
eval rate:            45.74 tokens/s
```

**Comment by tjbck** [comment]
fyi, `ghcr.io/open-webui/open-webui:main` will also pull the latest as per the previous comment.

**Comment by misterjice** [comment]
=) They say they fixed it!   =)  YAY!

🎨 Image Generation Error: Resolved a persistent issue causing errors with 'get_automatic1111_api_auth()' to ensure smooth image generation workflows.

**Comment by tjbck** [comment]
personally verified that it works on my machine, but do keep us updated 😅

**Comment by misterjice** [comment]
> personally verified that it works on my machine, but do keep us updated 😅

Totally working again!  Thanx =)
